#pragma once
#define MITHBRIDGE2_NVS_WIFI_SSID_KEY "W_SSID"
#define MITHBRIDGE2_NVS_WIFI_PSK_KEY "W_PSK"
#define MITHBRIDGE2_NVS_INFLUX_LINE_HTTPS_URL_KEY "ILH_URL"
#define MITHBRIDGE2_NVS_INFLUX_LINE_HTTPS_AUTH_KEY "ILH_AUTH"
