#pragma once

#define XIAO_ESP32C6_EXT_ANTENNA_RFSWITCH_ENABLE_GPIO (3)
#define XIAO_ESP32C6_EXT_ANTENNA_RFSWITCH_ENABLE_LEVEL (0)
#define XIAO_ESP32C6_EXT_ANTENNA_RFSWITCH_ENABLE_DELAY (100)
#define XIAO_ESP32C6_EXT_ANTENNA_RFSWITCH_EXT_ANT_GPIO (14)
#define XIAO_ESP32C6_EXT_ANTENNA_RFSWITCH_EXT_ANT_LEVEL (1)