name: Build and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile-and-release:
    runs-on: ubuntu-latest
    
    container:
      image: espressif/idf:v6.0.1
      options: --workdir /workspace 

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: . 

      - name: Run build script
        run: |
          . /opt/esp/idf/export.sh
          chmod +x ./build.esp32c6.xiao_external-antenna.sh
          ./build.esp32c6.xiao_external-antenna.sh

      - name: Generate date tag
        id: date_tag
        run: |
          TAG=$(date +'%Y%m%d%H%M')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.date_tag.outputs.tag }}
          name: Release ${{ steps.date_tag.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            dist/*.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}